# Model configuration parameters for running ARTIS pipeline on a local machine

# Sourced from scripts 01-clean-model-inputs and 02-artis-pipeline

# R packages required ------------------------------------------------------
library(artis)
library(data.table)
library(magrittr)
library(glue)
library(dplyr)
library(stringr)
library(tidyr)
#library(Matrix)
#library(parallel)
library(reticulate)
#library(slam)
#library(tidyverse)
#library(doParallel)
#library(aws.s3)
library(arrow)
#library(countrycode)
library(glue)
#library(qs2)
library(rfishbase)

# Set up Start date for finding no solution countries
start_date <- Sys.Date()
artis_version <- "v2.0"

# Input data directory paths --------------------------------------------------
datadir_raw <- "/Users/theamarks/Documents/UW-SAFS/ARTIS/data/model_inputs_raw_2.0"
# Directory for inputs to create the ARTIS database
datadir <- "~/Documents/UW-SAFS/ARTIS/data/model_inputs_2.0_FAO"
baci_version <- "202501"
tradedatadir <- file.path(datadir_raw, "baci_raw") 

# Model output directory paths --------------------------------------------
# Directory where ARTIS database will be generated
outdir <- "~/Documents/UW-SAFS/ARTIS/data/outputs_2.0_FAO"

# Don't change this bit #############
# Path for sub folder within outputs that will contain all country-level solutions
# to mass balance equation, solved using the python solver "quadprog"
outdir_quadprog <- file.path(outdir, "quadprog_snet")
# Path for sub folder within outputs that will contain all country-level solutions
# to mass balance equation, solved using the python solver "cvxopt"
outdir_cvxopt <- file.path(outdir, "cvxopt_snet")
# Path for collecting ARTIS database files
outdir_snet <- file.path(outdir, "snet")

# Development drafts and temporary files ---------------------------------
devdir <- "./AM_local/dev-artis-2.0"

# Postprocessing output directory paths -----------------------------------
outdir_attribute <- file.path(outdir, "attribute_tables")
outdir_sql <- file.path(outdir, "sql_database")

# 01-clean-model-inputs parameters --------------------------------
# Model Mode for 01-clean-model-inputs - TRUE fo#r SAU; FALSE for FAO
running_sau <- FALSE
## Set TRUE if new SeaLifeBase/FishBase data collection needed for 01-clean-model-inputs:
need_new_fb_slb <- FALSE


# AM - I think this is leftover code - can set HS year and year for running tests
test <- FALSE
test_year <- c()

# 02-artis-pipeline parameters ------------------------------------
# set years to run - empty if all years [c()], [c(2017)] or [c(2017,2020)] for subset of years
test_years <- c(2023) 
#test_years <- c(2017)
#test_years <- c()
# set model estimate - "min", "midpoint", "max" - default is "midpoint"
estimate_data_type <- "midpoint"
# Set production data type variable ["SAU"] or ["FAO"] - 02-artis-pipeline
prod_data_type <- "FAO"
dev_mode <- FALSE

# hs_version_run is set in 02-artis-pipeline because of current `artis-hpc` setup

# Create HS version / year assignments -----------------------------------

# Only change df_years when incorporating new HS version
# List of possible HS versions: HS96, HS02, HS07, HS12, HS17

# change this when ingesting new data with new years represented 
max_year <- 2023

# List of possible HS versions: HS96, HS02, HS07, HS12, HS17
# No need to do HS92 when using BACI though as that data starts in 1996
df_years <- data.frame(HS_year = c(rep("96", length(1996:max_year)),
                                   rep("02", length(2002:max_year)),
                                   rep("07", length(2007:max_year)),
                                   rep("12", length(2012:max_year)),
                                   rep("17", length(2017:max_year))),
                                   # add new HS version here
                       analysis_year = c(1996:max_year, 
                                          2002:max_year, 
                                          2007:max_year,
                                          2012:max_year, 
                                          2017:max_year
                                          # add new HS version here
                                        ))

## NOTE: If updating df_years here - you also need to update in ./R/initial_variable_setup.R which 
# creates and makes df_years available for running all functions in 02-artis-pipeline.R

# Create ARTIS directory architecture ------------------------------------

# Creates output and suboutput folders. Does not include HS version and year within these folders.

# Creating folder for clean model input data
if (!dir.exists(datadir)) {
  dir.create(datadir)
} else {
  warning(glue::glue("Directory datadir `{datadir}` already exists!"))
}

# Creating the sub folder for all country-level solutions generated by the python
# solver quadprog. Will delete folder if it already exists
if (dir.exists(outdir_quadprog)) {
  warning("quadprog output folder already exists, all contents are being deleted to create an empty folder.")
}
dir.create(outdir_quadprog)

# Creating the sub folder for all country-level solutions generated by the python
# solver quadprog. Will delete folder if it already exists
if (dir.exists(outdir_cvxopt)) {
  warning("cvxopt output folder already exists, all contents are being deleted to create an empty folder.")
}
dir.create(outdir_cvxopt)

# Creating the output folder for all ARTIS database files, will delete folder
# if it already exists
if(dir.exists(outdir_snet)) {
  warning("ARTIS snet output folder already exists, all contents are being deleted to create an empty folder.")
  #unlink(outdir_snet, recursive = TRUE)
}
dir.create(outdir_snet)

# create attribute directory if doesn't exist
if (!dir.exists(outdir_attribute)) { dir.create(outdir_attribute) }

# create attribute directory if doesn't exist
if (!dir.exists(outdir_sql)) { dir.create(outdir_sql) }

# 02-artis-pipeline python environment -----------------------------------
# Linking python environment set up during installation for use in the pipeline
#python_path <- file.path(getwd(), "venv", "bin", "python3")
#use_python(python_path, required = TRUE)

python_path <- file.path(getwd(), "venv")
reticulate::use_virtualenv(python_path, required = TRUE)

# empty AWS values --------------------------------------------------------
# need explicit empty AWS values when running locally - do not change
artis_bucket <- ""
artis_bucket_region <- ""

# Demo Mode -----------------------------------------------------------------
# Not sure if working AM 2025-04-28
# Will determine if the ARTIS pipeline functions are run with the demo variables
# or to run functions to create the ARTIS database for all years and HS versions
# TRUE or FALSE explicitly required for several conditionals within model functions
demo_run <- FALSE

# If running a test environment with specific codes scinames this variable should be true else false
# test <- FALSE
# test_year <- 2018
# test_hs <- "12"
# 
# if(test == TRUE){
#   test_scinames <- read.csv("demo/sciname_shrimps_prawns.csv") %>%
#     select(sciname) %>%
#     distinct() %>%
#     pull(sciname)
#   
#   test_codes <- c("030617", "160529", "160521", "030627", "030616", "030626")
# }else{}


